export const HOME_FETCH_HOME_SECTIONS_BEGIN = 'HOME_FETCH_HOME_SECTIONS_BEGIN';
export const HOME_FETCH_HOME_SECTIONS_SUCCESS = 'HOME_FETCH_HOME_SECTIONS_SUCCESS';
export const HOME_FETCH_HOME_SECTIONS_FAILURE = 'HOME_FETCH_HOME_SECTIONS_FAILURE';
export const HOME_FETCH_HOME_SECTIONS_DISMISS_ERROR = 'HOME_FETCH_HOME_SECTIONS_DISMISS_ERROR';
