export const GENERAL_FETCH_AUTOCOMPLETE_BEGIN = 'GENERAL_FETCH_AUTOCOMPLETE_BEGIN';
export const GENERAL_FETCH_AUTOCOMPLETE_SUCCESS = 'GENERAL_FETCH_AUTOCOMPLETE_SUCCESS';
export const GENERAL_FETCH_AUTOCOMPLETE_FAILURE = 'GENERAL_FETCH_AUTOCOMPLETE_FAILURE';
export const GENERAL_FETCH_AUTOCOMPLETE_DISMISS_ERROR = 'GENERAL_FETCH_AUTOCOMPLETE_DISMISS_ERROR';
export const GENERAL_FETCH_CATEGORIES_BEGIN = 'GENERAL_FETCH_CATEGORIES_BEGIN';
export const GENERAL_FETCH_CATEGORIES_SUCCESS = 'GENERAL_FETCH_CATEGORIES_SUCCESS';
export const GENERAL_FETCH_CATEGORIES_FAILURE = 'GENERAL_FETCH_CATEGORIES_FAILURE';
export const GENERAL_FETCH_CATEGORIES_DISMISS_ERROR = 'GENERAL_FETCH_CATEGORIES_DISMISS_ERROR';
